spring:
  application:
    name: service-center

server:
  port: 2001

eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:2002/eureka/
  instance:
    preferIpAddress: true

