eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone:  http://localhost:2001/eureka/,http://localhost:2002/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-b:
      path: /api-b/**
      serviceId: service-hi
