eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone:  http://localhost:2001/eureka/,http://localhost:2002/eureka/
server:
  port: 8763
spring:
  application:
    name: service-feign
feign:
  hystrix:
    enabled: true
