eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone:  http://localhost:2000/eureka/
server:
  port: 8762
spring:
  application:
    name: service-hi



